#pragma once

#include "sdk_errors.h"

#include "lan.h"
#include "flash_memory_map.h"
#include "Protobufs/AutoGenerated/C/flash_config_data.pb.h"

/*************************************************************
 * MACROS
 ************************************************************/
#define NUM_FALLBACK_SERVERS    ( 10 )

#define DOES_THIS_WORK          ( sizeof(FlashConfigData) )

/*************************************************************
 * GLOBAL VARIABLES
 ************************************************************/
extern FlashConfigData g_persistent_conf;

/*************************************************************
 * PUBLIC FUNCTIONS
 ************************************************************/
ret_code_t FlashConfigData_Init(void);
uint8_t FlashConfigData_IsInitalized(void);

// Only ever used by bootloader right before jumping to app code
ret_code_t FlashConfigData_Deinit(void);

// Returns 1 if the data is valid, 0 otherwise
uint8_t FlashConfigData_Validate(void);

void FlashConfigData_Print(void);

ret_code_t FlashConfigData_WriteBack(void);

ret_code_t FlashConfigData_RestoreFromSwap(void);
