__THIS_DIR := $(patsubst %/,%,$(dir $(realpath $(lastword $(MAKEFILE_LIST)))))

NANOPB_DIR := $(__THIS_DIR)/../nanopb
PROTOC     := $(NANOPB_DIR)/generator/protoc

# Directory where .proto files are located
PROTO_SRC_DIR := $(__THIS_DIR)

# Directory where .pb.h and .pb.c files will be generated
PROTO_BUILD_DIR := $(PROTO_SRC_DIR)/AutoGenerated

PB_C_BUILD_DIR  := $(PROTO_BUILD_DIR)/C
PB_PY_BUILD_DIR := $(PROTO_BUILD_DIR)/Py

# List of .proto files
PROTO_SRC_FILES += $(wildcard $(PROTO_SRC_DIR)/*.proto)

# Need to include this or protoc will complain
PROTOC_INCLUDES += -I$(NANOPB_DIR)/generator/proto
PROTOC_INCLUDES += -I$(PROTO_SRC_DIR)

# Generated C sources and headers from .proto files
PROTO_C_FILES  := $(addprefix $(PB_C_BUILD_DIR)/, $(notdir $(PROTO_SRC_FILES:.proto=.pb.c)))
PROTO_H_FILES  := $(addprefix $(PB_C_BUILD_DIR)/, $(notdir $(PROTO_SRC_FILES:.proto=.pb.h)))

# Need to include this for python or it will cause an import error
PROTO_SRC_FILES += $(NANOPB_DIR)/generator/proto/nanopb.proto

# Generated python sources from .proto files
PROTO_PY_FILES := $(addprefix $(PB_PY_BUILD_DIR)/, $(notdir $(PROTO_SRC_FILES:.proto=.py)))

vpath %.proto $(sort $(dir $(PROTO_SRC_FILES)))

NANOPB_SRC_FILES += $(NANOPB_DIR)/pb_encode.c
NANOPB_SRC_FILES += $(NANOPB_DIR)/pb_decode.c
NANOPB_SRC_FILES += $(NANOPB_DIR)/pb_common.c

NANOPB_INCLUDES := $(NANOPB_DIR)
